/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ContextApi,
  InsightsApi,
  JobApi,
  OidcTokenManagementApi,
  PipelineApi,
  PolicyManagementApi,
  ProjectApi,
  ScheduleApi,
  UserApi,
  WebhookApi,
  WorkflowApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { CircleCiCustom } from "./client-custom";

export class CircleCi extends CircleCiCustom {
  readonly context: ContextApi;
  readonly insights: InsightsApi;
  readonly job: JobApi;
  readonly oidcTokenManagement: OidcTokenManagementApi;
  readonly pipeline: PipelineApi;
  readonly policyManagement: PolicyManagementApi;
  readonly project: ProjectApi;
  readonly schedule: ScheduleApi;
  readonly user: UserApi;
  readonly webhook: WebhookApi;
  readonly workflow: WorkflowApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.context = new ContextApi(configuration);
    this.insights = new InsightsApi(configuration);
    this.job = new JobApi(configuration);
    this.oidcTokenManagement = new OidcTokenManagementApi(configuration);
    this.pipeline = new PipelineApi(configuration);
    this.policyManagement = new PolicyManagementApi(configuration);
    this.project = new ProjectApi(configuration);
    this.schedule = new ScheduleApi(configuration);
    this.user = new UserApi(configuration);
    this.webhook = new WebhookApi(configuration);
    this.workflow = new WorkflowApi(configuration);
  }

}
