/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An artifact
 * @export
 * @interface Artifact
 */
export interface Artifact {
    /**
     * The artifact path.
     * @type {string}
     * @memberof Artifact
     */
    'path': string;
    /**
     * The index of the node that stored the artifact.
     * @type {number}
     * @memberof Artifact
     */
    'node_index': number;
    /**
     * The URL to download the artifact contents.
     * @type {string}
     * @memberof Artifact
     */
    'url': string;
}

