/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BundleDiff
 */
export interface BundleDiff {
    /**
     * 
     * @type {Array<string>}
     * @memberof BundleDiff
     */
    'created'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BundleDiff
     */
    'deleted'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BundleDiff
     */
    'modified'?: Array<string>;
}

