/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContextCreateNewContextRequestOwnerOneOf } from './context-create-new-context-request-owner-one-of';
import { ContextCreateNewContextRequestOwnerOneOf1 } from './context-create-new-context-request-owner-one-of1';

/**
 * @type ContextCreateNewContextRequestOwner
 * @export
 */
export type ContextCreateNewContextRequestOwner = ContextCreateNewContextRequestOwnerOneOf | ContextCreateNewContextRequestOwnerOneOf1;


