/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContextListEnvironmentVariablesResponseItemsInner
 */
export interface ContextListEnvironmentVariablesResponseItemsInner {
    /**
     * The name of the environment variable
     * @type {string}
     * @memberof ContextListEnvironmentVariablesResponseItemsInner
     */
    'variable': string;
    /**
     * The date and time the environment variable was created.
     * @type {string}
     * @memberof ContextListEnvironmentVariablesResponseItemsInner
     */
    'created_at': string;
    /**
     * The date and time the environment variable was updated
     * @type {string}
     * @memberof ContextListEnvironmentVariablesResponseItemsInner
     */
    'updated_at': string;
    /**
     * ID of the context (UUID)
     * @type {string}
     * @memberof ContextListEnvironmentVariablesResponseItemsInner
     */
    'context_id': string;
}

