/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContextUpdateEnvironmentVariableRequest
 */
export interface ContextUpdateEnvironmentVariableRequest {
    /**
     * The value of the environment variable
     * @type {string}
     * @memberof ContextUpdateEnvironmentVariableRequest
     */
    'value': string;
}

