/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContextGetInformationResponse
 */
export interface ContextGetInformationResponse {
    /**
     * The unique ID of the context.
     * @type {string}
     * @memberof ContextGetInformationResponse
     */
    'id': string;
    /**
     * The user defined name of the context.
     * @type {string}
     * @memberof ContextGetInformationResponse
     */
    'name': string;
    /**
     * The date and time the context was created.
     * @type {string}
     * @memberof ContextGetInformationResponse
     */
    'created_at': string;
}

