/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Decision } from './decision';
import { DecisionLogMetadata } from './decision-log-metadata';

/**
 * 
 * @export
 * @interface DecisionLog
 */
export interface DecisionLog {
    /**
     * 
     * @type {string}
     * @memberof DecisionLog
     */
    'created_at'?: string;
    /**
     * 
     * @type {Decision}
     * @memberof DecisionLog
     */
    'decision'?: Decision;
    /**
     * 
     * @type {string}
     * @memberof DecisionLog
     */
    'id'?: string;
    /**
     * 
     * @type {DecisionLogMetadata}
     * @memberof DecisionLog
     */
    'metadata'?: DecisionLogMetadata;
    /**
     * policy-name-to-hash-map
     * @type {{ [key: string]: string; }}
     * @memberof DecisionLog
     */
    'policies'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof DecisionLog
     */
    'time_taken_ms'?: number;
}

