/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DecisionLogMetadataVcs } from './decision-log-metadata-vcs';

/**
 * 
 * @export
 * @interface DecisionLogMetadata
 */
export interface DecisionLogMetadata {
    /**
     * 
     * @type {number}
     * @memberof DecisionLogMetadata
     */
    'build_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof DecisionLogMetadata
     */
    'project_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DecisionLogMetadata
     */
    'ssh_rerun'?: boolean;
    /**
     * 
     * @type {DecisionLogMetadataVcs}
     * @memberof DecisionLogMetadata
     */
    'vcs'?: DecisionLogMetadataVcs;
}

