/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metrics for a single org metrics.
 * @export
 * @interface InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
 */
export interface InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics {
    /**
     * The total number of runs, including runs that are still on-hold or running.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
     */
    'total_runs': number;
    /**
     * Total duration, in seconds.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
     */
    'total_duration_secs': number;
    /**
     * The total credits consumed over the current timeseries interval.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
     */
    'total_credits_used': number;
    /**
     * 
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
     */
    'success_rate': number;
    /**
     * The average number of runs per day.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgDataMetrics
     */
    'throughput': number;
}

