/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metrics relating to the duration of runs for a workflow.
 * @export
 * @interface InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
 */
export interface InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics {
    /**
     * The minimum duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
     */
    'min': number;
    /**
     * The median duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
     */
    'median': number;
    /**
     * The max duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
     */
    'max': number;
    /**
     * The 95th percentile duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
     */
    'p95': number;
    /**
     * The total duration, in seconds, added across a group of runs.
     * @type {number}
     * @memberof InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics
     */
    'total': number;
}

