/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metrics relating to the duration of runs for a workflow.
 * @export
 * @interface InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
 */
export interface InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics {
    /**
     * The minimum duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'min': number;
    /**
     * The mean duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'mean': number;
    /**
     * The median duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'median': number;
    /**
     * The 95th percentile duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'p95': number;
    /**
     * The max duration, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'max': number;
    /**
     * The standard deviation, in seconds, among a group of runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInnerMetricsDurationMetrics
     */
    'standard_deviation': number;
}

