/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Project branches response.
 * @export
 * @interface InsightsListProjectBranchesResponse
 */
export interface InsightsListProjectBranchesResponse {
    /**
     * The unique ID of the organization
     * @type {any}
     * @memberof InsightsListProjectBranchesResponse
     */
    'org_id': any;
    /**
     * The unique ID of the project
     * @type {any}
     * @memberof InsightsListProjectBranchesResponse
     */
    'project_id': any;
    /**
     * A list of all the branches for a given project.
     * @type {Array<string>}
     * @memberof InsightsListProjectBranchesResponse
     */
    'branches': Array<string>;
}

