/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner } from './insights-get-project-workflow-test-metrics-response-most-failed-tests-inner';
import { InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner } from './insights-get-project-workflow-test-metrics-response-test-runs-inner';

/**
 * Project level test metrics response
 * @export
 * @interface InsightsGetProjectWorkflowTestMetricsResponse
 */
export interface InsightsGetProjectWorkflowTestMetricsResponse {
    /**
     * The average number of tests executed per run
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'average_test_count': number;
    /**
     * Metrics for the most frequently failing tests
     * @type {Array<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner>}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'most_failed_tests': Array<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner>;
    /**
     * The number of tests with the same success rate being omitted from most_failed_tests
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'most_failed_tests_extra': number;
    /**
     * Metrics for the slowest running tests
     * @type {Array<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner>}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'slowest_tests': Array<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner>;
    /**
     * The number of tests with the same duration rate being omitted from slowest_tests
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'slowest_tests_extra': number;
    /**
     * The total number of test runs
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'total_test_runs': number;
    /**
     * Test counts grouped by pipeline number and workflow id
     * @type {Array<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner>}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponse
     */
    'test_runs': Array<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner>;
}

