/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerMetrics } from './insights-get-summary-metrics-with-trends-response-org-project-data-inner-metrics';
import { InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends } from './insights-get-summary-metrics-with-trends-response-org-project-data-inner-trends';

/**
 * 
 * @export
 * @interface InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInner
 */
export interface InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInner {
    /**
     * The name of the project.
     * @type {string}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInner
     */
    'project_name': string;
    /**
     * 
     * @type {InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerMetrics}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInner
     */
    'metrics': InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerMetrics;
    /**
     * 
     * @type {InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInner
     */
    'trends': InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends;
}

