/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetRecentWorkflowRunsResponseItemsInner } from './insights-get-recent-workflow-runs-response-items-inner';

/**
 * Paginated recent workflow runs.
 * @export
 * @interface InsightsGetRecentWorkflowRunsResponse
 */
export interface InsightsGetRecentWorkflowRunsResponse {
    /**
     * Recent workflow runs.
     * @type {Array<InsightsGetRecentWorkflowRunsResponseItemsInner>}
     * @memberof InsightsGetRecentWorkflowRunsResponse
     */
    'items': Array<InsightsGetRecentWorkflowRunsResponseItemsInner>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof InsightsGetRecentWorkflowRunsResponse
     */
    'next_page_token': string;
}

