/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectWorkflowJobMetricsResponseItemsInner } from './insights-get-project-workflow-job-metrics-response-items-inner';

/**
 * Paginated workflow job summary metrics.
 * @export
 * @interface InsightsGetProjectWorkflowJobMetricsResponse
 */
export interface InsightsGetProjectWorkflowJobMetricsResponse {
    /**
     * Job summary metrics.
     * @type {Array<InsightsGetProjectWorkflowJobMetricsResponseItemsInner>}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponse
     */
    'items': Array<InsightsGetProjectWorkflowJobMetricsResponseItemsInner>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponse
     */
    'next_page_token': string;
}

