/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Test counts for a given pipeline number
 * @export
 * @interface InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
 */
export interface InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts {
    /**
     * The number of tests with the error status
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    'error': number;
    /**
     * The number of tests with the failure status
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    'failure': number;
    /**
     * The number of tests with the skipped status
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    'skipped': number;
    /**
     * The number of tests with the success status
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    'success': number;
    /**
     * The total number of tests
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    'total': number;
}

