/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metrics aggregated across all workflows and branches for a project.
 * @export
 * @interface InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
 */
export interface InsightsGetProjectSummaryMetricsResponseProjectDataMetrics {
    /**
     * The total number of runs, including runs that are still on-hold or running.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
     */
    'total_runs': number;
    /**
     * Total duration, in seconds.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
     */
    'total_duration_secs': number;
    /**
     * The total credits consumed over the current timeseries interval.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
     */
    'total_credits_used': number;
    /**
     * 
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
     */
    'success_rate': number;
    /**
     * The average number of runs per day.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataMetrics
     */
    'throughput': number;
}

