/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetFlakyTestsResponseFlakyTestsInner } from './insights-get-flaky-tests-response-flaky-tests-inner';

/**
 * Flaky tests response
 * @export
 * @interface InsightsGetFlakyTestsResponse
 */
export interface InsightsGetFlakyTestsResponse {
    /**
     * A list of all instances of flakes. Note that a test is no longer considered flaky after 2 weeks have passed without a flake. Each flake resets this timer.
     * @type {Array<InsightsGetFlakyTestsResponseFlakyTestsInner>}
     * @memberof InsightsGetFlakyTestsResponse
     */
    'flaky-tests': Array<InsightsGetFlakyTestsResponseFlakyTestsInner>;
    /**
     * A count of unique tests that have failed. If your project has N tests that have flaked multiple times each, this will be equal to N.
     * @type {number}
     * @memberof InsightsGetFlakyTestsResponse
     */
    'total-flaky-tests': number;
}

