/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectSummaryMetricsResponseProjectDataMetrics } from './insights-get-project-summary-metrics-response-project-data-metrics';
import { InsightsGetProjectSummaryMetricsResponseProjectDataTrends } from './insights-get-project-summary-metrics-response-project-data-trends';

/**
 * Metrics and trends data aggregated for a given project.
 * @export
 * @interface InsightsGetProjectSummaryMetricsResponseProjectData
 */
export interface InsightsGetProjectSummaryMetricsResponseProjectData {
    /**
     * 
     * @type {InsightsGetProjectSummaryMetricsResponseProjectDataMetrics}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectData
     */
    'metrics': InsightsGetProjectSummaryMetricsResponseProjectDataMetrics;
    /**
     * 
     * @type {InsightsGetProjectSummaryMetricsResponseProjectDataTrends}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectData
     */
    'trends': InsightsGetProjectSummaryMetricsResponseProjectDataTrends;
}

