/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectWorkflowMetricsResponseItemsInnerMetrics } from './insights-get-project-workflow-metrics-response-items-inner-metrics';

/**
 * 
 * @export
 * @interface InsightsGetProjectWorkflowMetricsResponseItemsInner
 */
export interface InsightsGetProjectWorkflowMetricsResponseItemsInner {
    /**
     * The name of the workflow.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    'name': string;
    /**
     * 
     * @type {InsightsGetProjectWorkflowMetricsResponseItemsInnerMetrics}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    'metrics': InsightsGetProjectWorkflowMetricsResponseItemsInnerMetrics;
    /**
     * The timestamp of the first build within the requested reporting window.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    'window_start': string;
    /**
     * The timestamp of the last build within the requested reporting window.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    'window_end': string;
    /**
     * The unique ID of the project
     * @type {any}
     * @memberof InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    'project_id': any;
}

