/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metric trends aggregated across all workflows and branches for a project.
 * @export
 * @interface InsightsGetProjectSummaryMetricsResponseProjectDataTrends
 */
export interface InsightsGetProjectSummaryMetricsResponseProjectDataTrends {
    /**
     * The trend value for total number of runs.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataTrends
     */
    'total_runs': number;
    /**
     * Trend value for total duration.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataTrends
     */
    'total_duration_secs': number;
    /**
     * The trend value for total credits consumed.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataTrends
     */
    'total_credits_used': number;
    /**
     * The trend value for the success rate.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataTrends
     */
    'success_rate': number;
    /**
     * Trend value for the average number of runs per day.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectDataTrends
     */
    'throughput': number;
}

