/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetrics } from './insights-get-project-workflow-job-metrics-response-items-inner-metrics';

/**
 * 
 * @export
 * @interface InsightsGetProjectWorkflowJobMetricsResponseItemsInner
 */
export interface InsightsGetProjectWorkflowJobMetricsResponseItemsInner {
    /**
     * The name of the job.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponseItemsInner
     */
    'name': string;
    /**
     * 
     * @type {InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetrics}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponseItemsInner
     */
    'metrics': InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetrics;
    /**
     * The timestamp of the first build within the requested reporting window.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponseItemsInner
     */
    'window_start': string;
    /**
     * The timestamp of the last build within the requested reporting window.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowJobMetricsResponseItemsInner
     */
    'window_end': string;
}

