/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Metrics aggregated across a workflow or branchfor a project.
 * @export
 * @interface InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics
 */
export interface InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics {
    /**
     * The total credits consumed over the current timeseries interval.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics
     */
    'total_credits_used': number;
    /**
     * The 95th percentile duration among a group of workflow runs.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics
     */
    'p95_duration_secs': number;
    /**
     * The total number of runs, including runs that are still on-hold or running.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics
     */
    'total_runs': number;
    /**
     * 
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics
     */
    'success_rate': number;
}

