/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Trends for a single project, across all branches.
 * @export
 * @interface InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends
 */
export interface InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends {
    /**
     * The trend value for total credits consumed.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends
     */
    'total_credits_used': number;
    /**
     * Trend value for total duration.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends
     */
    'total_duration_secs': number;
    /**
     * The trend value for total number of runs.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends
     */
    'total_runs': number;
    /**
     * The trend value for the success rate.
     * @type {number}
     * @memberof InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataInnerTrends
     */
    'success_rate': number;
}

