/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Trends aggregated across a workflow or branch for a project.
 * @export
 * @interface InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends
 */
export interface InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends {
    /**
     * The trend value for total credits consumed.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends
     */
    'total_credits_used': number;
    /**
     * The 95th percentile duration among a group of workflow runs.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends
     */
    'p95_duration_secs': number;
    /**
     * The trend value for total number of runs.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends
     */
    'total_runs': number;
    /**
     * The trend value for the success rate.
     * @type {number}
     * @memberof InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends
     */
    'success_rate': number;
}

