/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InsightsGetFlakyTestsResponseFlakyTestsInner
 */
export interface InsightsGetFlakyTestsResponseFlakyTestsInner {
    /**
     * 
     * @type {number}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'time-wasted'?: number;
    /**
     * The date and time when workflow was created.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'workflow-created-at': string;
    /**
     * The ID of the workflow associated with the provided test counts
     * @type {any}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'workflow-id': any;
    /**
     * The class the test belongs to.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'classname': string;
    /**
     * The number of the pipeline.
     * @type {number}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'pipeline-number': number;
    /**
     * The name of the workflow.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'workflow-name': string;
    /**
     * The name of the test.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'test-name': string;
    /**
     * The name of the job.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'job-name': string;
    /**
     * The number of the job.
     * @type {number}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'job-number': number;
    /**
     * The number of times the test flaked.
     * @type {number}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'times-flaked': number;
    /**
     * The source of the test.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'source': string;
    /**
     * The file the test belongs to.
     * @type {string}
     * @memberof InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    'file': string;
}

