/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
 */
export interface InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner {
    /**
     * The 95th percentile duration, in seconds, among a group of test runs.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'p95_duration': number;
    /**
     * The total number of times the test was run.
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'total_runs': number;
    /**
     * The class the test belongs to.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'classname': string;
    /**
     * The number of times the test failed
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'failed_runs': number;
    /**
     * Whether the test is flaky.
     * @type {boolean}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'flaky': boolean;
    /**
     * The source of the test.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'source': string;
    /**
     * The file the test belongs to.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'file': string;
    /**
     * The name of the job.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'job_name': string;
    /**
     * The name of the test.
     * @type {string}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner
     */
    'test_name': string;
}

