/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts } from './insights-get-project-workflow-test-metrics-response-test-runs-inner-test-counts';

/**
 * 
 * @export
 * @interface InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner
 */
export interface InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner {
    /**
     * The number of the pipeline associated with the provided test counts
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner
     */
    'pipeline_number': number;
    /**
     * The ID of the workflow associated with the provided test counts
     * @type {any}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner
     */
    'workflow_id': any;
    /**
     * The success rate calculated from test counts
     * @type {number}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner
     */
    'success_rate': number;
    /**
     * 
     * @type {InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts}
     * @memberof InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner
     */
    'test_counts': InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts;
}

