/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Info about a pipeline the job is a part of.
 * @export
 * @interface JobGetDetailsResponsePipeline
 */
export interface JobGetDetailsResponsePipeline {
    /**
     * The unique ID of the pipeline.
     * @type {string}
     * @memberof JobGetDetailsResponsePipeline
     */
    'id': string;
}

