/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the context.
 * @export
 * @interface JobGetDetailsResponseContextsInner
 */
export interface JobGetDetailsResponseContextsInner {
    /**
     * The name of the context.
     * @type {string}
     * @memberof JobGetDetailsResponseContextsInner
     */
    'name': string;
}

