/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about an organization.
 * @export
 * @interface JobGetDetailsResponseOrganization
 */
export interface JobGetDetailsResponseOrganization {
    /**
     * The name of the organization.
     * @type {string}
     * @memberof JobGetDetailsResponseOrganization
     */
    'name': string;
}

