/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Info about the latest workflow the job was a part of.
 * @export
 * @interface JobGetDetailsResponseLatestWorkflow
 */
export interface JobGetDetailsResponseLatestWorkflow {
    /**
     * The unique ID of the workflow.
     * @type {string}
     * @memberof JobGetDetailsResponseLatestWorkflow
     */
    'id': string;
    /**
     * The name of the workflow.
     * @type {string}
     * @memberof JobGetDetailsResponseLatestWorkflow
     */
    'name': string;
}

