/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about executor used for a job.
 * @export
 * @interface JobGetDetailsResponseExecutor
 */
export interface JobGetDetailsResponseExecutor {
    /**
     * Resource class name.
     * @type {string}
     * @memberof JobGetDetailsResponseExecutor
     */
    'resource_class': string;
    /**
     * Executor type.
     * @type {string}
     * @memberof JobGetDetailsResponseExecutor
     */
    'type'?: string;
}

