/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobGetDetailsResponseContextsInner } from './job-get-details-response-contexts-inner';
import { JobGetDetailsResponseExecutor } from './job-get-details-response-executor';
import { JobGetDetailsResponseLatestWorkflow } from './job-get-details-response-latest-workflow';
import { JobGetDetailsResponseMessagesInner } from './job-get-details-response-messages-inner';
import { JobGetDetailsResponseOrganization } from './job-get-details-response-organization';
import { JobGetDetailsResponseParallelRunsInner } from './job-get-details-response-parallel-runs-inner';
import { JobGetDetailsResponsePipeline } from './job-get-details-response-pipeline';
import { JobGetDetailsResponseProject } from './job-get-details-response-project';

/**
 * Job Details
 * @export
 * @interface JobGetDetailsResponse
 */
export interface JobGetDetailsResponse {
    /**
     * URL of the job in CircleCI Web UI.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'web_url': string;
    /**
     * 
     * @type {JobGetDetailsResponseProject}
     * @memberof JobGetDetailsResponse
     */
    'project': JobGetDetailsResponseProject;
    /**
     * Info about parallels runs and their status.
     * @type {Array<JobGetDetailsResponseParallelRunsInner>}
     * @memberof JobGetDetailsResponse
     */
    'parallel_runs': Array<JobGetDetailsResponseParallelRunsInner>;
    /**
     * The date and time the job started.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'started_at': string;
    /**
     * 
     * @type {JobGetDetailsResponseLatestWorkflow}
     * @memberof JobGetDetailsResponse
     */
    'latest_workflow': JobGetDetailsResponseLatestWorkflow;
    /**
     * The name of the job.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'name': string;
    /**
     * 
     * @type {JobGetDetailsResponseExecutor}
     * @memberof JobGetDetailsResponse
     */
    'executor': JobGetDetailsResponseExecutor;
    /**
     * A number of parallel runs the job has.
     * @type {number}
     * @memberof JobGetDetailsResponse
     */
    'parallelism': number;
    /**
     * The current status of the job.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'status': JobGetDetailsResponseStatusEnum;
    /**
     * The number of the job.
     * @type {number}
     * @memberof JobGetDetailsResponse
     */
    'number': number;
    /**
     * 
     * @type {JobGetDetailsResponsePipeline}
     * @memberof JobGetDetailsResponse
     */
    'pipeline': JobGetDetailsResponsePipeline;
    /**
     * Duration of a job in milliseconds.
     * @type {number}
     * @memberof JobGetDetailsResponse
     */
    'duration': number;
    /**
     * The time when the job was created.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'created_at': string;
    /**
     * Messages from CircleCI execution platform.
     * @type {Array<JobGetDetailsResponseMessagesInner>}
     * @memberof JobGetDetailsResponse
     */
    'messages': Array<JobGetDetailsResponseMessagesInner>;
    /**
     * List of contexts used by the job.
     * @type {Array<JobGetDetailsResponseContextsInner>}
     * @memberof JobGetDetailsResponse
     */
    'contexts': Array<JobGetDetailsResponseContextsInner>;
    /**
     * 
     * @type {JobGetDetailsResponseOrganization}
     * @memberof JobGetDetailsResponse
     */
    'organization': JobGetDetailsResponseOrganization;
    /**
     * The time when the job was placed in a queue.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'queued_at': string;
    /**
     * The time when the job stopped.
     * @type {string}
     * @memberof JobGetDetailsResponse
     */
    'stopped_at'?: string;
}

type JobGetDetailsResponseStatusEnum = 'success' | 'running' | 'not_run' | 'failed' | 'retried' | 'queued' | 'not_running' | 'infrastructure_fail' | 'timedout' | 'on_hold' | 'terminated-unknown' | 'blocked' | 'canceled' | 'unauthorized'


