/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PipelineContinueExecutionRequestParametersValue } from './pipeline-continue-execution-request-parameters-value';

/**
 * The information you can supply when triggering a pipeline.
 * @export
 * @interface PipelineTriggerNewPipelineRequest
 */
export interface PipelineTriggerNewPipelineRequest {
    /**
     * An object containing pipeline parameters and their values.
     * @type {{ [key: string]: PipelineContinueExecutionRequestParametersValue; }}
     * @memberof PipelineTriggerNewPipelineRequest
     */
    'parameters'?: { [key: string]: PipelineContinueExecutionRequestParametersValue; };
    /**
     * The branch where the pipeline ran. The HEAD commit on this branch was used for the pipeline. Note that `branch` and `tag` are mutually exclusive. To trigger a pipeline for a PR by number use `pull/<number>/head` for the PR ref or `pull/<number>/merge` for the merge ref (GitHub only).
     * @type {string}
     * @memberof PipelineTriggerNewPipelineRequest
     */
    'branch'?: string;
    /**
     * The tag used by the pipeline. The commit that this tag points to was used for the pipeline. Note that `branch` and `tag` are mutually exclusive.
     * @type {string}
     * @memberof PipelineTriggerNewPipelineRequest
     */
    'tag'?: string;
}

