/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The user who triggered the Pipeline.
 * @export
 * @interface PipelineTriggerActor
 */
export interface PipelineTriggerActor {
    /**
     * The login information for the user on the VCS.
     * @type {string}
     * @memberof PipelineTriggerActor
     */
    'login': string;
    /**
     * URL to the user\'s avatar on the VCS
     * @type {string}
     * @memberof PipelineTriggerActor
     */
    'avatar_url': string;
}

