/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Pipeline1 } from './pipeline1';

/**
 * List of pipelines
 * @export
 * @interface PipelineGetAllPipelinesResponse
 */
export interface PipelineGetAllPipelinesResponse {
    /**
     * 
     * @type {Array<Pipeline1>}
     * @memberof PipelineGetAllPipelinesResponse
     */
    'items': Array<Pipeline1>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof PipelineGetAllPipelinesResponse
     */
    'next_page_token': string;
}

