/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The configuration strings for the pipeline.
 * @export
 * @interface PipelineGetConfigurationByIdResponse
 */
export interface PipelineGetConfigurationByIdResponse {
    /**
     * The source configuration for the pipeline, before any config compilation has been performed. If there is no config, then this field will be empty.
     * @type {string}
     * @memberof PipelineGetConfigurationByIdResponse
     */
    'source': string;
    /**
     * The compiled configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline\'s configuration, then this field may be empty.
     * @type {string}
     * @memberof PipelineGetConfigurationByIdResponse
     */
    'compiled': string;
    /**
     * The setup configuration for the pipeline used for Setup Workflows. If there were errors processing the pipeline\'s configuration or if setup workflows are not enabled, then this field should not exist
     * @type {string}
     * @memberof PipelineGetConfigurationByIdResponse
     */
    'setup-config'?: string;
    /**
     * The compiled setup configuration for the pipeline, after all orb expansion has been performed. If there were errors processing the pipeline\'s setup workflows, then this field may be empty.
     * @type {string}
     * @memberof PipelineGetConfigurationByIdResponse
     */
    'compiled-setup-config'?: string;
}

