/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A pipeline creation response.
 * @export
 * @interface PipelineTriggerNewPipelineResponse
 */
export interface PipelineTriggerNewPipelineResponse {
    /**
     * The unique ID of the pipeline.
     * @type {string}
     * @memberof PipelineTriggerNewPipelineResponse
     */
    'id': string;
    /**
     * The current state of the pipeline.
     * @type {string}
     * @memberof PipelineTriggerNewPipelineResponse
     */
    'state': PipelineTriggerNewPipelineResponseStateEnum;
    /**
     * The number of the pipeline.
     * @type {number}
     * @memberof PipelineTriggerNewPipelineResponse
     */
    'number': number;
    /**
     * The date and time the pipeline was created.
     * @type {string}
     * @memberof PipelineTriggerNewPipelineResponse
     */
    'created_at': string;
}

type PipelineTriggerNewPipelineResponseStateEnum = 'created' | 'errored' | 'setup-pending' | 'setup' | 'pending'


