/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Policy
 */
export interface Policy {
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    'content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    'created_by'?: string;
    /**
     * 
     * @type {string}
     * @memberof Policy
     */
    'name'?: string;
}

