/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the VCS that hosts the project source code.
 * @export
 * @interface ProjectGetBySlugResponseVcsInfo
 */
export interface ProjectGetBySlugResponseVcsInfo {
    /**
     * URL to the repository hosting the project\'s code
     * @type {string}
     * @memberof ProjectGetBySlugResponseVcsInfo
     */
    'vcs_url': string;
    /**
     * The VCS provider
     * @type {string}
     * @memberof ProjectGetBySlugResponseVcsInfo
     */
    'provider': ProjectGetBySlugResponseVcsInfoProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectGetBySlugResponseVcsInfo
     */
    'default_branch': string;
}

type ProjectGetBySlugResponseVcsInfoProviderEnum = 'Bitbucket' | 'CircleCI' | 'GitHub'


