/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EnvironmentVariable } from './environment-variable';

/**
 * 
 * @export
 * @interface ProjectListEnvVarValuesResponse
 */
export interface ProjectListEnvVarValuesResponse {
    /**
     * 
     * @type {Array<EnvironmentVariable>}
     * @memberof ProjectListEnvVarValuesResponse
     */
    'items': Array<EnvironmentVariable>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof ProjectListEnvVarValuesResponse
     */
    'next_page_token': string;
}

