/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * message response
 * @export
 * @interface ProjectDeleteEnvironmentVariableResponse
 */
export interface ProjectDeleteEnvironmentVariableResponse {
    /**
     * A human-readable message
     * @type {string}
     * @memberof ProjectDeleteEnvironmentVariableResponse
     */
    'message': string;
}

