/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectGetBySlugResponseVcsInfo } from './project-get-by-slug-response-vcs-info';

/**
 * NOTE: The definition of Project is subject to change.
 * @export
 * @interface ProjectGetBySlugResponse
 */
export interface ProjectGetBySlugResponse {
    /**
     * Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped. For projects that use GitLab or GitHub App, use `circleci` as the `vcs-slug`, replace `org-name` with the organization ID (found in Organization Settings), and replace `repo-name` with the project ID (found in Project Settings).
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'slug': string;
    /**
     * The name of the project
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'id': string;
    /**
     * The name of the organization the project belongs to
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'organization_name': string;
    /**
     * The slug of the organization the project belongs to
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'organization_slug': string;
    /**
     * The id of the organization the project belongs to
     * @type {string}
     * @memberof ProjectGetBySlugResponse
     */
    'organization_id': string;
    /**
     * 
     * @type {ProjectGetBySlugResponseVcsInfo}
     * @memberof ProjectGetBySlugResponse
     */
    'vcs_info': ProjectGetBySlugResponseVcsInfo;
}

