/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An environment variable is a map containing a value and an optional timestamp.
 * @export
 * @interface ProjectGetMaskedEnvVarResponse
 */
export interface ProjectGetMaskedEnvVarResponse {
    /**
     * The name of the environment variable.
     * @type {string}
     * @memberof ProjectGetMaskedEnvVarResponse
     */
    'name': string;
    /**
     * The value of the environment variable.
     * @type {string}
     * @memberof ProjectGetMaskedEnvVarResponse
     */
    'value': string;
    /**
     * The creation timestamp of the environment variable.
     * @type {any}
     * @memberof ProjectGetMaskedEnvVarResponse
     */
    'created-at'?: any;
}

