/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RestrictionCreated
 */
export interface RestrictionCreated {
    /**
     * UUID of the project restriction
     * @type {string}
     * @memberof RestrictionCreated
     */
    'id'?: string;
    /**
     * Deprecated - For \"project\" restrictions read the project ID from \"restriction_value\" instead.  UUID of the project used in a project restriction. 
     * @type {string}
     * @memberof RestrictionCreated
     */
    'project_id'?: string;
    /**
     * Contains a human-readable reference for the restriction. For \"project\" restrictions this is the name of the project.  May be null. 
     * @type {string}
     * @memberof RestrictionCreated
     */
    'name'?: string;
    /**
     * Type of the restriction
     * @type {string}
     * @memberof RestrictionCreated
     */
    'restriction_type'?: RestrictionCreatedRestrictionTypeEnum;
    /**
     * Value used to evaluate the restriction
     * @type {string}
     * @memberof RestrictionCreated
     */
    'restriction_value'?: string;
}

type RestrictionCreatedRestrictionTypeEnum = 'project' | 'expression'


