/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PipelineContinueExecutionRequestParametersValue } from './pipeline-continue-execution-request-parameters-value';
import { ScheduleCreateNewScheduleRequestTimetable } from './schedule-create-new-schedule-request-timetable';
import { UserProperty } from './user-property';

/**
 * A schedule response
 * @export
 * @interface ScheduleCreateNewScheduleResponse
 */
export interface ScheduleCreateNewScheduleResponse {
    /**
     * Description of the schedule.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'description': string;
    /**
     * Pipeline parameters represented as key-value pairs. Must contain branch or tag.
     * @type {{ [key: string]: PipelineContinueExecutionRequestParametersValue; }}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'parameters': { [key: string]: PipelineContinueExecutionRequestParametersValue; };
    /**
     * The unique ID of the schedule.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'id': string;
    /**
     * 
     * @type {ScheduleCreateNewScheduleRequestTimetable}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'timetable': ScheduleCreateNewScheduleRequestTimetable;
    /**
     * The date and time the pipeline was last updated.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'updated-at': string;
    /**
     * Name of the schedule.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'name': string;
    /**
     * The date and time the pipeline was created.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'created-at': string;
    /**
     * The project-slug for the schedule
     * @type {string}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'project-slug': string;
    /**
     * 
     * @type {UserProperty}
     * @memberof ScheduleCreateNewScheduleResponse
     */
    'actor': UserProperty;
}

