/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PipelineContinueExecutionRequestParametersValue } from './pipeline-continue-execution-request-parameters-value';
import { ScheduleCreateNewScheduleRequestTimetable } from './schedule-create-new-schedule-request-timetable';

/**
 * The parameters for a create schedule request
 * @export
 * @interface ScheduleCreateNewScheduleRequest
 */
export interface ScheduleCreateNewScheduleRequest {
    /**
     * Description of the schedule.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleRequest
     */
    'description'?: string;
    /**
     * Pipeline parameters represented as key-value pairs. Must contain branch or tag.
     * @type {{ [key: string]: PipelineContinueExecutionRequestParametersValue; }}
     * @memberof ScheduleCreateNewScheduleRequest
     */
    'parameters': { [key: string]: PipelineContinueExecutionRequestParametersValue; };
    /**
     * Name of the schedule.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleRequest
     */
    'name': string;
    /**
     * 
     * @type {ScheduleCreateNewScheduleRequestTimetable}
     * @memberof ScheduleCreateNewScheduleRequest
     */
    'timetable': ScheduleCreateNewScheduleRequestTimetable;
    /**
     * The attribution-actor of the scheduled pipeline.
     * @type {string}
     * @memberof ScheduleCreateNewScheduleRequest
     */
    'attribution-actor': ScheduleCreateNewScheduleRequestAttributionActorEnum;
}

type ScheduleCreateNewScheduleRequestAttributionActorEnum = 'current' | 'system'


