/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ScheduleCreateNewScheduleRequestTimetableAnyOf } from './schedule-create-new-schedule-request-timetable-any-of';
import { ScheduleCreateNewScheduleRequestTimetableAnyOf1 } from './schedule-create-new-schedule-request-timetable-any-of1';

/**
 * @type ScheduleCreateNewScheduleRequestTimetable
 * Timetable that specifies when a schedule triggers.
 * @export
 */
export type ScheduleCreateNewScheduleRequestTimetable = ScheduleCreateNewScheduleRequestTimetableAnyOf | ScheduleCreateNewScheduleRequestTimetableAnyOf1;


