/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Schedule } from './schedule';

/**
 * A sequence of schedules
 * @export
 * @interface ScheduleGetAllSchedulesResponse
 */
export interface ScheduleGetAllSchedulesResponse {
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof ScheduleGetAllSchedulesResponse
     */
    'items': Array<Schedule>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof ScheduleGetAllSchedulesResponse
     */
    'next_page_token': string;
}

