/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The attribution actor who will run the scheduled pipeline.
 * @export
 * @interface UserProperty
 */
export interface UserProperty {
    /**
     * The unique ID of the user.
     * @type {string}
     * @memberof UserProperty
     */
    'id': string;
    /**
     * The login information for the user on the VCS.
     * @type {string}
     * @memberof UserProperty
     */
    'login': string;
    /**
     * The name of the user.
     * @type {string}
     * @memberof UserProperty
     */
    'name': string;
}

