/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Webhook } from './webhook';

/**
 * A list of webhooks
 * @export
 * @interface WebhookListMatchingScopeResponse
 */
export interface WebhookListMatchingScopeResponse {
    /**
     * 
     * @type {Array<Webhook>}
     * @memberof WebhookListMatchingScopeResponse
     */
    'items': Array<Webhook>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof WebhookListMatchingScopeResponse
     */
    'next_page_token': string;
}

