/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The scope in which the relevant events that will trigger webhooks
 * @export
 * @interface WebhookCreateOutboundWebhookRequestScope
 */
export interface WebhookCreateOutboundWebhookRequestScope {
    /**
     * ID of the scope being used (at the moment, only project ID is supported)
     * @type {string}
     * @memberof WebhookCreateOutboundWebhookRequestScope
     */
    'id': string;
    /**
     * Type of the scope being used
     * @type {string}
     * @memberof WebhookCreateOutboundWebhookRequestScope
     */
    'type': WebhookCreateOutboundWebhookRequestScopeTypeEnum;
}

type WebhookCreateOutboundWebhookRequestScopeTypeEnum = 'project'


