/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A response to rerunning a workflow
 * @export
 * @interface WorkflowRerunWorkflowResponse
 */
export interface WorkflowRerunWorkflowResponse {
    /**
     * The ID of the newly-created workflow.
     * @type {string}
     * @memberof WorkflowRerunWorkflowResponse
     */
    'workflow_id': string;
}

