/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkflowApproveJobdefaultResponse
 */
export interface WorkflowApproveJobdefaultResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkflowApproveJobdefaultResponse
     */
    'message'?: string;
}

