/*
CircleCI API

This describes the resources that make up the CircleCI API v2.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Job } from './job';

/**
 * 
 * @export
 * @interface WorkflowGetJobsResponse
 */
export interface WorkflowGetJobsResponse {
    /**
     * 
     * @type {Array<Job>}
     * @memberof WorkflowGetJobsResponse
     */
    'items': Array<Job>;
    /**
     * A token to pass as a `page-token` query parameter to return the next page of results.
     * @type {string}
     * @memberof WorkflowGetJobsResponse
     */
    'next_page_token': string;
}

